
```{r}
library(tidyverse)
```

```{r}
library(LaF)
```

```{r}
widths <- read.csv("Extracted pages from 2021_YRBS_Data_Users_Guide_508.xlsx - Sheet2.csv", header=TRUE)
```

```{r}
dat0 <- laf_open_fwf("XXH2021_YRBS_Data.dat", column_widths=widths$Length, column_names=widths$Variable, column_types=rep("string", nrow(widths)))
```

```{r}
dat <- dat0[,]; str(dat)
```

```{r}
v2k <- c('Q1',	'Q2',	'Q3',	'Q4',	'RACEETH',	'Q8', 'QN8',	'Q9', 'QN9', 'Q10', 'QN10',	'Q11', 'QN11',	'Q12', 'QN12',	'Q13',	'Q14', 'QN14',	'Q15', 'QN15',	'Q16', 'QN16',	'Q17', 'QN17',	'Q18',	'Q19', 'QN19',	'Q20', 'QN20',	'Q21',	'Q22', 'QN22',	'Q23', 'QN23',	'Q24', 'QN24',	'Q25', 'QN25',	'Q26', 'QN26',	'Q27',	'Q28', 'QN28',	'Q29',	'Q30', 'QN30',	'Q31', 'QN31',	'Q32', 'QN32',	'Q33', 'QN33',	'Q34', 'QN34',	'Q35',	'Q36',	'Q37', 'QN37',	'Q38', 'QN38',	'Q40', 'QN40',	'Q41',	'Q42', 'QN42',	'Q43',	'Q44', 'QN44',	'Q45', 'QN45',	'Q46', 'QN46',	'Q47',	'Q48',	'Q49', 'QN49',	'Q50', 'QN50',	'Q51',	'Q52', 'QN52',	'Q53', 'QN53',	'Q54',	'Q55', 'QN55',	'Q56', 'QN56',	'Q57', 'QN57',	'Q58', 'QN58',	'Q59', 'QN59',	'Q60',	'Q61',	'Q62', 'QN62',	'Q63', 'QN63',	'Q64',	'Q65',	'Q68',	'Q69',	'Q70',	'Q71',	'Q72',	'Q73',	'Q74',	'Q76',	'Q77',	'Q78',	'Q79',	'Q80',	'Q82', 'QN82',	'Q83', 'QN83',	'Q84', 'QN84',	'Q85', 'QN85', 'Q86',	'Q87', 'QN87',	'Q88', 'QN88',	'Q89',	'Q93', 'QN93',	'Q95',	'Q96', 'QN96', 'QN97', 'QN99',	'Q99')
```

```{r}
'%!in%' <- Negate('%in%') #not in function. shows which variables are not in the dataset. should be 0 
```

```{r}
v2k[which(v2k %!in% names(dat))]
```

```{r}
sdat <- dat[,v2k] 
```

```{r}
sdat$Q2 <- factor(sdat$Q2, levels=rev(1:2), labels=rev(c("Female", "Male")))
sdat$QN85 <- factor(sdat$QN85, levels=rev(1:2), labels=rev(c("Yes", "No")))
```

```{r}
tab <- table(sdat$Q2); tab
ptab <- prop.table(tab); ptab
barplot(ptab*100)
```

```{r}
table(sdat$Q2, sdat$QN85, useNA="ifany")
tab <- table(sdat$Q2, sdat$QN85) 
ptab <- prop.table(tab); ptab
```


